import { useEffect, useState } from "react";
import { BookOpenCheck, CalendarDays, CalendarRange, ChevronLeft, ChevronRight, Clock3, Database, GraduationCap, Home, MapPin, ShieldCheck, UserRound, X } from "lucide-react";
import { initialCourses } from "./initialCourses";
const ADMIN_URL = "https://xiamen-tax-assistant.w2350370952.chatgpt.site/admin";

const weekNames = ["星期一","星期二","星期三","星期四","星期五","星期六","星期日"];
const palette = { tax:{label:"税务课程",color:"#2f6fed",soft:"#eaf1ff"}, english:{label:"英语课程",color:"#15966f",soft:"#e7f7f1"}, digital:{label:"数字与智能",color:"#7657d6",soft:"#f0ecff"}, other:{label:"其他课程",color:"#7b8798",soft:"#eef1f4"} };
const iso = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const dateOf = s => new Date(`${s}T12:00:00`);
const addDays = (d,n) => { const x=new Date(d); x.setDate(x.getDate()+n); return x; };
const monday = d => addDays(d,1-(d.getDay()||7));
const firstMonth = d => new Date(d.getFullYear(),d.getMonth(),1,12);
const addMonths = (d,n) => new Date(d.getFullYear(),d.getMonth()+n,1,12);

export default function App(){
  const [tab,setTab]=useState("today");
  const [courses,setCourses]=useState(initialCourses);
  const [version,setVersion]=useState({label:"v1.0",updated_at:"2026-07-20T15:00:00Z"});
  const [selected,setSelected]=useState(null);
  const [now,setNow]=useState(new Date());
  const first=initialCourses[0].date;
  const initialFocus=iso(new Date())<first?dateOf(first):new Date();
  const [weekAnchor,setWeekAnchor]=useState(initialFocus);
  const [monthAnchor,setMonthAnchor]=useState(firstMonth(initialFocus));
  const [selectedDay,setSelectedDay]=useState(iso(initialFocus));
  const [synced,setSynced]=useState(false);

  useEffect(()=>{ const timer=setInterval(()=>setNow(new Date()),1000); fetch("/api/courses").then(r=>r.ok?r.json():Promise.reject()).then(d=>{ if(d.courses?.length)setCourses(d.courses); if(d.version)setVersion(d.version); setSynced(true); }).catch(()=>setSynced(false)); return()=>clearInterval(timer); },[]);
  const today=iso(now), todayCourses=courses.filter(c=>c.date===today);
  const next=courses.find(c=>`${c.date}T${c.start_time}`>`${today}T${now.toTimeString().slice(0,5)}`);
  const weekStart=monday(weekAnchor), weekDays=Array.from({length:7},(_,i)=>addDays(weekStart,i));
  const monthStart=firstMonth(monthAnchor), gridStart=monday(monthStart), monthDays=Array.from({length:42},(_,i)=>addDays(gridStart,i));
  const nav=[{id:"today",label:"今日",icon:Home},{id:"week",label:"周课表",icon:CalendarDays},{id:"month",label:"月视图",icon:CalendarRange},{id:"profile",label:"我的",icon:UserRound}];

  return <div className="shell">
    <aside className="sidebar"><button className="brand" onClick={()=>setTab("today")}><b>MT</b><span><strong>厦国会</strong><small>税务专硕助手</small></span></button><nav>{nav.map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}><n.icon size={19}/>{n.label}</button>)}</nav><a className="admin" href={ADMIN_URL} target="_blank" rel="noreferrer"><ShieldCheck size={17}/>管理员入口</a></aside>
    <main>
      {tab==="today"&&<section className="page"><Header eyebrow="TODAY'S FOCUS" title={`${["星期日","星期一","星期二","星期三","星期四","星期五","星期六"][now.getDay()]}，专注当下。`} sub={`${now.getFullYear()}年${now.getMonth()+1}月${now.getDate()}日 · 厦门国家会计学院`}/>{next&&<div className="next"><Clock3/><span><small>下一节课程 · {next.course_name}</small><strong>{next.date} {next.weekday} · {next.start_time}</strong></span></div>}<Panel title="今日课程" count={todayCourses.length}>{todayCourses.length?<div className="course-list">{todayCourses.map(c=><CourseCard key={c.id} c={c} onClick={()=>setSelected(c)}/>)}</div>:<Empty first={courses[0]?.date} onGo={()=>setTab("week")}/>}</Panel></section>}
      {tab==="week"&&<section className="page"><Header eyebrow="WEEKLY SCHEDULE" title="周课表" sub={`${weekDays[0].getMonth()+1}月${weekDays[0].getDate()}日 – ${weekDays[6].getMonth()+1}月${weekDays[6].getDate()}日`} actions={<Pager view="week" prev={()=>setWeekAnchor(addDays(weekAnchor,-7))} next={()=>setWeekAnchor(addDays(weekAnchor,7))} onWeek={()=>{setWeekAnchor(initialFocus);setTab("week")}} onMonth={()=>{setMonthAnchor(firstMonth(initialFocus));setSelectedDay(iso(initialFocus));setTab("month")}}/>}/><div className="week-scroll"><div className="week-grid"><div className="corner">时段</div>{weekDays.map((d,i)=><div className={`day-head ${iso(d)===today?"today":""}`} key={iso(d)}><span>{weekNames[i]}</span><b>{d.getDate()}</b></div>)}{["上午","下午"].map(period=><WeekRow key={period} period={period} days={weekDays} courses={courses} select={setSelected}/>)}</div></div><MobileWeek days={weekDays} courses={courses} today={today} select={setSelected}/><Legend/></section>}
      {tab==="month"&&<section className="page"><Header eyebrow="MONTHLY CALENDAR" title={`${monthStart.getFullYear()}年${monthStart.getMonth()+1}月`} sub="按月查看全部课程安排" actions={<Pager view="month" prev={()=>{const d=addMonths(monthAnchor,-1);setMonthAnchor(d);setSelectedDay(iso(d));}} next={()=>{const d=addMonths(monthAnchor,1);setMonthAnchor(d);setSelectedDay(iso(d));}} onWeek={()=>{setWeekAnchor(initialFocus);setTab("week")}} onMonth={()=>{setMonthAnchor(firstMonth(initialFocus));setSelectedDay(iso(initialFocus));setTab("month")}}/>}/><div className="month-calendar"><div className="weekdays">{weekNames.map(x=><span key={x}>{x.replace("星期","周")}</span>)}</div><div className="month-grid">{monthDays.map(d=>{const key=iso(d), dayCourses=courses.filter(c=>c.date===key);return <div key={key} className={`month-cell ${d.getMonth()!==monthStart.getMonth()?"outside":""} ${key===today?"today":""} ${key===selectedDay?"selected":""}`}><button className="date-btn" onClick={()=>setSelectedDay(key)}><b>{d.getDate()}</b>{dayCourses.length>0&&<small>{dayCourses.length}节</small>}</button><div className="month-courses">{dayCourses.map(c=>{const p=palette[c.course_type]||palette.other;return <button aria-label={c.course_name} title={c.course_name} key={c.id} style={{"--color":p.color,"--soft":p.soft}} onClick={()=>{setSelectedDay(key);setSelected(c)}}><i/><span>{c.course_name}</span></button>})}</div></div>})}</div></div><Panel title={`${selectedDay.replaceAll("-",".")} 课程`} count={courses.filter(c=>c.date===selectedDay).length}>{courses.some(c=>c.date===selectedDay)?<div className="course-list">{courses.filter(c=>c.date===selectedDay).map(c=><CourseCard key={c.id} c={c} onClick={()=>setSelected(c)}/>)}</div>:<div className="day-empty">当天暂无课程</div>}</Panel><Legend/></section>}
      {tab==="profile"&&<section className="page"><div className="hero"><GraduationCap size={34}/><div><small>2025级全日制 MT</small><h1>税务专硕课程空间</h1><p>把课程安排变成清晰、可靠的日常。</p></div></div><div className="stats"><Stat icon={<BookOpenCheck/>} label="当前课程" value={courses.length} note="条已发布安排"/><Stat icon={<Database/>} label="当前版本" value={version?.label||"v1.0"} note={synced?"已连接最新数据":"正在使用本地课程备份"}/><Stat icon={<Clock3/>} label="更新时间" value={(version?.updated_at||"").slice(0,10).replaceAll("-",".")||"—"} note="管理员审核后生效"/></div><div className="safe"><ShieldCheck/><span><strong>管理员专属发布</strong><small>只有管理员可以上传、审核和发布PDF。</small></span><a href={ADMIN_URL} target="_blank" rel="noreferrer">进入后台</a></div></section>}
    </main>
    <nav className="bottom">{nav.map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}><n.icon size={20}/><span>{n.label}</span></button>)}</nav>
    {selected&&<Modal c={selected} close={()=>setSelected(null)}/>} 
  </div>;
}

function Header({eyebrow,title,sub,actions}){return <header><div><em>{eyebrow}</em><h1>{title}</h1><p>{sub}</p></div>{actions}</header>}
function Pager({prev,next,onWeek,onMonth,view}){const [open,setOpen]=useState(false);return <div className="pager"><button aria-label="上一页" onClick={prev}><ChevronLeft/></button><button className="current-picker" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>当前</button><button aria-label="下一页" onClick={next}><ChevronRight/></button>{open&&<div className="view-menu"><button className={view==="week"?"active":""} onClick={()=>{onWeek();setOpen(false)}}><CalendarDays size={17}/><span><b>当前周</b><small>查看周课表</small></span></button><button className={view==="month"?"active":""} onClick={()=>{onMonth();setOpen(false)}}><CalendarRange size={17}/><span><b>当前月</b><small>查看月课表</small></span></button></div>}</div>}
function Panel({title,count,children}){return <div className="panel"><div className="panel-head"><h2>{title}</h2><span>{count} 节</span></div>{children}</div>}
function Empty({first,onGo}){return <div className="empty"><BookOpenCheck/><h3>今日暂无课程</h3><p>{first?`本学期课程将于 ${first} 开始`:"暂无课程安排"}</p><button onClick={onGo}>浏览本学期安排</button></div>}
function CourseCard({c,onClick}){const p=palette[c.course_type]||palette.other;return <button className="course" style={{"--color":p.color,"--soft":p.soft}} onClick={onClick}><i/><div><small>{p.label}</small><h3>{c.course_name}</h3><p><span><UserRound size={14}/>{c.teacher||"教师待定"}</span><span><Clock3 size={14}/>{c.start_time}–{c.end_time}</span>{c.classroom&&<span><MapPin size={14}/>{c.classroom}</span>}</p></div><b>{c.period}</b></button>}
function WeekRow({period,days,courses,select}){return <><div className="period"><b>{period}</b><small>{period==="上午"?"08:30":"14:30"}</small></div>{days.map(d=><div className="week-cell" key={`${iso(d)}${period}`}>{courses.filter(c=>c.date===iso(d)&&c.period===period).map(c=>{const p=palette[c.course_type]||palette.other;return <button key={c.id} style={{"--color":p.color,"--soft":p.soft}} onClick={()=>select(c)}><b>{c.course_name}</b><span>{c.teacher}</span></button>})}</div>)}</>}
function MobileWeek({days,courses,today,select}){return <div className="mobile-week">{days.map((d,index)=>{const date=iso(d), dayCourses=courses.filter(c=>c.date===date);return <article className={date===today?"today":""} key={date}><div className="mobile-day-head"><span><b>{weekNames[index]}</b><small>{d.getMonth()+1}月{d.getDate()}日</small></span><em>{dayCourses.length} 节</em></div>{dayCourses.length?<div className="mobile-day-courses">{dayCourses.map(c=>{const p=palette[c.course_type]||palette.other;return <button key={c.id} style={{"--color":p.color,"--soft":p.soft}} onClick={()=>select(c)}><i/><span><strong>{c.course_name}</strong><small>{c.period} {c.start_time}–{c.end_time} · {c.teacher||"教师待定"}</small></span></button>})}</div>:<p className="mobile-no-course">暂无课程</p>}</article>})}</div>}
function Legend(){return <div className="legend">{Object.values(palette).map(p=><span key={p.label}><i style={{background:p.color}}/>{p.label}</span>)}</div>}
function Stat({icon,label,value,note}){return <article><span>{icon}</span><small>{label}</small><strong>{value}</strong><em>{note}</em></article>}
function Modal({c,close}){const p=palette[c.course_type]||palette.other;return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><button className="close" onClick={close}><X/></button><small style={{color:p.color}}>{p.label}</small><h2>{c.course_name}</h2><dl><div><dt>日期</dt><dd>{c.date} · {c.weekday}</dd></div><div><dt>时间</dt><dd>{c.start_time}–{c.end_time}</dd></div><div><dt>教师</dt><dd>{c.teacher||"未填写"}</dd></div><div><dt>班级</dt><dd>{c.class_name||"未填写"}</dd></div><div><dt>教室</dt><dd>{c.classroom||"未填写"}</dd></div><div><dt>备注</dt><dd>{c.remark||"无"}</dd></div></dl></div></div>}
